name: pyTMD
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - notebook
  - ipyleaflet
  - numpy
  - scipy
  - pyproj
  - matplotlib
  - netCDF4
  - h5py
  - cartopy
  - pip:
     - git+https://github.com/tsutterley/read-ICESat-2.git
     - git+https://github.com/tsutterley/read-ATM1b-QFIT-binary.git
